# Generated by Django 5.1.4 on 2024-12-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api2', '0002_remove_user_username_user_last_login_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
